[package]
name = "async-redis-session"
version = "0.1.0"
authors = ["Jacob Rothstein <hi@jbr.me>"]
edition = "2018"

[dependencies]
redis = { version = "0.16.0", features = ["aio"] }
async-session = "1.0.2"
serde = "1.0.114"
serde_json = "1.0.56"
async-trait = "0.1.36"
http-types = "2.2.1"

[patch.crates-io]
async-session = { path = "../async-session" }#git = "https://github.com/jbr/async-session", branch = "tide" }
