[package]
name = "async-redis-session"
version = "0.1.0"
authors = ["Jacob Rothstein <hi@jbr.me>"]
edition = "2018"

[dependencies]
redis = { version = "0.16.0", features = ["aio"] }
async-session = "2.0.0"

[dev-dependencies]
async-std = { version = "1.6.2", features = ["attributes"] }
